src/design_notes/stream.md

The newest version is 0.3.4, and this technique ensures the links do not get outdated.

Link to 0.3 instead of 0.3.1

---

rfc-drafts/stream.md

This is still a WIP.
[Rendered](https://github.com/nellshamrell/wg-async-foundations/blob/update-stream-rfc/rfc-drafts/stream.md)

[DRAFT] Update stream rfc

---

rfc-drafts/stream.md

[Rendered](https://github.com/rust-lang/wg-async-foundations/blob/aa01041d7ee96b2306108c9af8f29293b0cfe174/rfc-drafts/stream.md)
[Language team notes](https://github.com/rust-lang/lang-team/blob/master/design-meeting-minutes/2020-08-26-stream-trait.md) on async stream design.
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

adds updates based on lang team meeting 2020-08-26

---

src/vision/how_to_vision.md
src/vision/status_quo/alan_runs_into_stack_trouble.md

@nikomatsakis This is the story I mentioned to you about large stack allocations caused by pinning large futures to the stack.

Add story of Alan running in trouble with large stack allocations

---

src/vision/status_quo/barbara_makes_their_first_steps_into_async.md
src/vision/status_quo/frederik_makes_their_first_steps_into_async.md

Hi! This is my experience as a newcomer to async in Rust. Niko might recognize some of these sentiments from me replying to his tweet asking for stories similar to this one surrounding async.
I haven't picked a character yet, as I feel like the character would have a very different experience depending on whether or not they've had previous experience with async in other languages. If I can assume that it not being mentioned means they don't have any experience with it, Alan would probably a decent choice. For now I've used my own name but I will replace it.
I took a very story like approach to writing this, I hope it's not too verbose.
[Rendered](https://github.com/Frederik-Baetens/wg-async-foundations/blob/status-quo-beginner/src/vision/status_quo/barbara_makes_their_first_steps_into_asy …

add status quo story: first steps into async

---

src/vision/status_quo/niklaus_wants_to_share_knowledge.md

Add a story

---

src/vision/status_quo/barbara_plays_with_async.md

This is a status quo story about Barbara and her first experiences with rust async.  It was developed mostly from my personal experiences, plus notes from a group discussion with some folks on a zoom "writing session" organized by Niko.
Of the current open issues, this one most closely matches #46.
This new story here is pretty similar to [Barbara makes their first foray into async](https://rust-lang.github.io/wg-async-foundations/vision/status_quo/barbara_makes_their_first_steps_into_async.html).   Both this story and that story start with Barbara in the same place, but they evolve a bit differently and focus in on different things.  My first inclination is to keep both stories, but we can certainly discuss if they are worth merging.   We might want to adjust the titles of these a bit to …

Add a status quo story about Barbara's first async playground

---

src/vision/status_quo/barbara_carefully_dismisses_embedded_future.md

[Rendered](https://github.com/jrvanwhy/wg-async-foundations/blob/bcdef/src/vision/status_quo/barbara_carefully_dismisses_embedded_future.md)
Barbara tries to implement an asynchronous API for embedded systems, and finds that `core::future::Future` has a very high overhead.

status quo: Barbara carefully dismisses embedded `Future`

---

src/vision/status_quo/barbara_tries_async_streams.md

This adds a status quo story for Barbara based on our experience using async streams in Nushell.

Add an async streams status quo for Barbara

---

src/design_docs/async_fn_in_traits.md
src/vision/characters.md
src/vision/characters/alan.md
src/vision/characters/barbara.md
src/vision/characters/grace.md
src/vision/characters/niklaus.md
src/vision/grace_waits_for_gdb_next.md
src/vision/how_to_vision/shiny_future.md
src/vision/how_to_vision/status_quo.md
src/vision/projects/DistriData.md
src/vision/projects/MonsterMesh.md
src/vision/projects/SLOW.md
src/vision/projects/TrafficMonitor.md
src/vision/projects/YouBuy.md
src/vision/projects/template.md
src/vision/shiny_future/template.md
src/vision/status_quo/alan_finds_database_drops_hard.md
src/vision/status_quo/alan_hates_writing_a_stream.md
src/vision/status_quo/alan_runs_into_stack_trouble.md
src/vision/status_quo/alan_started_trusting_the_rust_compiler_but_then_async.md
src/vision/status_quo/barbara_carefully_dismisses_embedded_future.md
src/vision/status_quo/barbara_makes_their_first_steps_into_async.md
src/vision/status_quo/barbara_plays_with_async.md
src/vision/status_quo/barbara_tries_async_streams.md
src/vision/status_quo/barbara_trims_a_stacktrace.md
src/vision/status_quo/grace_deploys_her_service.md
src/vision/status_quo/grace_wants_to_integrate_c_api.md
src/vision/status_quo/niklaus_wants_to_share_knowledge.md
src/vision/status_quo/template.md

Rework all FAQ Sections to use Headings instead of bullet lists

---

src/vision/status_quo/Alan_tries_to_debug_a_hang.md

I believe this captures the essence of #76 and may also touch on #75 a bit as some of that info could have been useful to Alan when trying to debug what's going on.

Add status quo story about Alan trying to debug an app hang

---

src/vision/status_quo/barbara_wants_async_insights.md

Written during [Vision Doc Writing Sessions](https://smallcultfollowing.com/babysteps/blog/2021/03/29/async-vision-doc-writing-sessions-iii/), along with others.
Related to #75.

Barbara wants async insights

---

src/vision/status_quo/alan_writes_a_web_framework.md

This PR contains a write-up of my experiences from https://github.com/rust-lang/wg-async-foundations/issues/78#issuecomment-808193936 
There is a bit of solutionising towards the end. I can rip that out if you want:
> Alan longs to be able to say "this function takes an async function as a callback" (`fn register_handler(handler: impl async Fn(state: &mut State) -> Result<Response, Error>)`) and have Rust elide the lifetimes for him, like how they are elided for async functions.
It's also super-trimmed-down compared to my full experiences, and we could probably flesh out the morals a bit better.

Borrowing arguments ("Alan writes a web framework")

---

.github/workflows/ci.yml

All this does is use rustdoc to run rust code blocks
but since we're ignoring all of the code blocks anyway,
there's no point in running `mdbook test`

Don't run "mdbook test" in CI

---

src/vision/status_quo/barbara_builds_an_async_executor.md

A "status quo" story about my first experience about writing an async executor.

Barbara builds an async executor

---

src/SUMMARY.md
src/vision/status_quo/alan_needs_async_in_traits.md
src/vision/status_quo/alan_tries_to_debug_a_hang.md

Result of the [async traits session](https://hackmd.io/TTD9uVNxQYKOF_5omKxogw) held on Apr 8, 2021.
Fixes https://github.com/rust-lang/wg-async-foundations/issues/82

status-quo story: Alan needs async in traits

---

src/vision/status_quo/alan_tries_a_socket_sink.md

Previously, indenting all bullet points by 4 spaces caused them to [render as preformatted code blocks](https://rust-lang.github.io/wg-async-foundations/vision/status_quo/alan_tries_a_socket_sink.html), requiring horizontal scrolling to read the bullet points, and breaking links and formatting. Dedenting them fixes this issue.
Just dedenting renders correctly in GitHub's markdown viewer, but I don't know if you need a blank line before/after the bullet block, to make it render properly in the site.

Fix formatting in "Alan tries using a socket Sink"

---

src/vision/shiny_future/barbara_makes_a_wish.md
src/vision/status_quo/alan_finds_database_drops_hard.md
src/vision/status_quo/alan_hates_writing_a_stream.md
src/vision/status_quo/alan_lost_the_world.md
src/vision/status_quo/alan_started_trusting_the_rust_compiler_but_then_async.md
src/vision/status_quo/alan_writes_a_web_framework.md
src/vision/status_quo/barbara_anguishes_over_http.md
src/vision/status_quo/barbara_carefully_dismisses_embedded_future.md
src/vision/status_quo/barbara_plays_with_async.md
src/vision/status_quo/grace_wants_to_integrate_c_api.md

* Removes `ignore` from code blocks which aren't needed
* Removes some template leftovers
* Improves formatting of some bullet points

Small cosmetic changes

---

src/vision/status_quo/barbara_compares_some_cpp_code.md

The technical conclusion of the specific example in this doc is similar to: https://github.com/rust-lang/wg-async-foundations/pull/132, but the story in general can be about how to compare rust async code and other languages async code (particularly c++20)

Barbara compares some cpp code (and has a performance problem)

---

src/vision/status_quo/barbara_needs_async_helpers.md

Written during [Vision Doc Writing Sessions](https://smallcultfollowing.com/babysteps/blog/2021/03/29/async-vision-doc-writing-sessions-iii/), along with other helpful folks.
Fixes #105

Barbara needs async helpers

---

src/vision/shiny_future/alan_switches_runtimes.md
src/vision/shiny_future/alans_trust_in_the_compiler_is_rewarded.md

A pair of shiny future stories sketching out an alternative path for Alan as he gets started, and also some ideas for how he might switch between runtimes.
This is partly based on the writing session we had yesterday, so co-author credit goes to @Mark-Simulacrum, @tmandry, @emmanuelantony2000, and @doc-jones.

[shiny future] Alan's trust in the compiler is rewarded, Alan switches runtimes

---

src/vision/shiny_future.md

When I went to check on some details of the shiny future purpose, I eventually found that the blog post was very useful, but wasn't linked on the shiny future index page. This is just a suggested addition :shrug:

Add link to shiny future blog post

---

src/vision/how_to_vision.md

We've been doing an amazing job with the status quo stories, but I think we're going to want more time to kick around shiny future. Giving us a bit more time.

extend end of brainstorming deadline to 2021-05-14

---

src/vision/shiny_future/barbara_enjoys_an_async_sandwich.md

[Rendered](https://github.com/seanmonstar/wg-async-foundations/blob/shiny-future-barbara-async-sandwich/src/vision/shiny_future/barbara_enjoys_an_async_sandwich.md)

shiny future: Barbara enjoys an async sandwich

---

src/vision/status_quo/barbara_battles_buffered_streams.md
src/vision/status_quo/barbara_battles_with_futures_unordered.md

Closes https://github.com/rust-lang/wg-async-foundations/issues/131

turn the futures-unordered footgun into a status quo story

---

src/vision/status_quo/barbara_writes_a_runtime_agnostic_lib.md

This is a story from the async vision story session of April 16, 2021.

status quo: Barbara writes a runtime-agnostic library

---

src/vision/status_quo/alan_misses_c_sharp_async.md

[Rendered](https://github.com/Nashenas88/wg-async-foundations/blob/f2cc60f61da71a3826dae686181845ba82662210/src/vision/status_quo/alan_misses_c_sharp_async.md)
I do have one todo left near the end. I wasn't sure if it was worth it to add an example of Alan trying to implement cancellation correctly or whether leaving it undone would show that it might be out of Alan's reach initially.
Also, should I add more C# examples earlier on to show where Alan is coming from?

status quo: Alan missing C# async

---

src/vision/characters/alan.md
src/vision/status_quo/alan_builds_a_task_scheduler.md

For https://github.com/rust-lang/wg-async-foundations/issues/150.
Any feedback would be appreciated!
Thanks in advance.

status_quo: add "variant Go", "alan builds a task scheduler"

---

src/vision/roadmap/polish.md

This change elaborates the desired impact from the polish area and also
sets an initial set of milestones to bring about this impact. We will
continue to refine these over time.

Refine polish section impact, define milestones

---

src/vision/roadmap.md
src/vision/roadmap/polish.md
src/welcome.md

This adds additional detail on the welcome page with links to the roadmap, and also establishes the convention of using 🛠️ to identify sections that include more how to help guidance.

Add more how to help guidance

---

src/SUMMARY.md
src/design_docs/async_stack_traces.md
src/vision/roadmap/polish/stacktraces.md

This adds a page describing the current state of async stack traces,
what some of the problems are, and some targetted changes that could
improve them.
Issue #251

Add design notes for async stack traces

---

src/design_docs/async_stack_traces.md

_Ref https://github.com/rust-lang/wg-async-foundations/issues/251_
This adds references from other languages to the async stack traces section. Thanks!

Add a references section to async stack traces

---

src/design_docs/async_stack_traces.md

Facebook did a five part series of blog posts on async stack traces in [folly]. This is in the context of C++, but it has a lot in common with what we might want for Rust so it's worth keeping a reference here.
[folly]: https://github.com/facebook/folly
Related to #251

[async-stacktraces] Add references to folly blogs

---

src/vision/roadmap.md
src/vision/roadmap/async_overloading.md
src/vision/roadmap/polish/sync_and_async.md

I'm volunteering myself to take point on this. Thanks!

Mark @yoshuawuyts as owner of "Async overloading"

---

src/vision/roadmap/polish/sync_and_async.md

This fills out some of the goals around sync and async code behaving the same.
This phrase can mean different things to different people, so the goal here is to call out those different things and try to provide more precise definitions where possible.
Several sections are under-developed, but these will be filled out in additional commits or PRs.

More detail about goals for sync and async code behave the same

---

src/SUMMARY.md
src/meetings.md
src/triage.md
src/welcome.md

To make it easier to keep track of which meetings are coming up when, we've consolidated all of our meetings details onto one page. We can also use this to schedule topics in advance.
Joint work with @tmandry

Add meetings page

---

src/vision/roadmap.md

This adds a landing page and marks the work as started.
I will work on a blog post to discuss together the milestone to add, do this job in sync I think will benefit to collect more ideas from people that are doing work where this initiative depends on.
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

docs: add async main and test charter description

---

src/welcome.md

This PR just adds a link to the HackMD organization so that people interested in joining can look at past meeting notes, the reading list, etc.

Add hackmd link

---

src/SUMMARY.md
src/glossary.md

This PR adds a glossary of acronyms commonly found in discussions of async language features. It currently just links to a couple of RFCs/issues, but could also include blog posts on these topics if we think that would be helpful.

Add a glossary

---

src/design_docs/async_stack_traces.md

Minor updates to point out progress on the symbol naming suggestion, and also to reference https://github.com/eholk/better-backtrace where some of the filtering and formatting ideas are being prototyped.

Add updates on symbol naming and better-backtrace prototype

---

src/meetings.md

My last push screwed up the link to the [10:00] time. This should address that.

fix [10:00] link
