rust-lang/wg-async

src/SUMMARY.md, src/design_notes/async_read_write.md, src/design_notes/mutex.md
This also fixes the async read/write link.
=> Add mutex blog link

book.toml, src/LICENSE-APACHE, src/LICENSE-MIT, src/design_docs/stream.md, src/vision.md, src/vision/roadmap.md
I noticed a few links that didn't work, I think these are correct.
Also, adding site-url allows mdbook's 404 support to work correctly when deployed on the website.
=> Fix some broken links.

src/SUMMARY.md, src/vision/applications.md, src/vision/applications/embedded.md, src/vision/applications/os.md, src/vision/characters.md, src/vision/characters/alan.md, src/vision/characters/barbara.md, src/vision/characters/grace.md, src/vision/characters/niklaus.md
This approach focuses the characters on the background they are coming from and divorces them from specific applications. In some cases, we have multiple variants. I removed the "axes" because they didn't seem to be adding much, and in fact were somewhat distracting.
[Rendered preview.](https://nikomatsakis.github.io/wg-async-foundations/vision/characters.html)
=> revamp characters

src/vision/status_quo.md
Talks a bit about coming to Rust w/ existing networking experience.
=> Expand Grace and networking

src/vision.md, src/vision/characters/alan.md, src/vision/how_to_vision.md, src/vision/shiny_future.md, src/vision/status_quo.md
[Preview](https://nikomatsakis.github.io/wg-async-foundations/)
=> minor improvements to vision doc wording etc

.github/ISSUE_TEMPLATE/-status-quo--story-issue.md
The link to Barbara's profile was broken.
=> Correct typo in Barbara's name

src/vision/characters/grace.md
Just found double `be able to` so removed one.
=> Fix typo in characters/grace.md

src/vision/status_quo/alan_hates_writing_a_stream.md
[Rendered](https://github.com/seanmonstar/wg-async-foundations/blob/status-quo-streaming-yuck/src/vision/status_quo/alan_hates_writing_a_stream.md)
=> status quo: Alan hates writing a Stream

src/vision/grace_waits_for_gdb_next.md
Written at tail end of group writing session hosted by niko, with useful input from other participants. (Especially point that Grace is the only character this really applies to...)
=> Add status quo story about Grace trying to use gdb to step through a program

src/vision/status_quo/grace_wants_to_integrate_c_api.md
Grace tries to create an async pipeline with a C-API that provides some limited async-like interfaces. She discovers some assimilation bias from C and C++, but manages to produce some working code for her and her team.
=> Status Quo: Grace integrates a C API

src/vision/status_quo/grace_tries_new_libraries.md
Please note that I'm neither a technical writer nor am I a native speaker. This is just a quick summary of the experiences I had while doing some stuff with kube-rs. It would be awesome to get some help to get this into a state where it actually could help you pals to improve the experience when using async code.
Thanks for this project btw :)
=> First draft: Tell Grace's story about a journey to a new library.

rfc-drafts/must_not_await_lint.md, src/design_docs/async_fn_in_traits.md, src/design_docs/stream.md, src/design_docs/yield_safe.md, src/vision/grace_waits_for_gdb_next.md, src/vision/status_quo/alan_finds_database_drops_hard.md, src/vision/status_quo/alan_hates_writing_a_stream.md, src/vision/status_quo/alan_lost_the_world.md, src/vision/status_quo/alan_runs_into_stack_trouble.md, src/vision/status_quo/alan_started_trusting_the_rust_compiler_but_then_async.md, src/vision/status_quo/alan_tries_to_debug_a_hang.md, src/vision/status_quo/alan_writes_a_web_framework.md, src/vision/status_quo/barbara_carefully_dismisses_embedded_future.md, src/vision/status_quo/barbara_plays_with_async.md, src/vision/status_quo/barbara_trims_a_stacktrace.md, src/vision/status_quo/grace_tries_new_libraries.md, src/vision/status_quo/grace_wants_to_integrate_c_api.md
=> Remove ignore directives from closing backtick blocks

src/vision/status_quo/barbara_anguishes_over_http.md
Written in collaboration with others during an async foundations vision doc [writing session](https://smallcultfollowing.com/babysteps/blog/2021/03/29/async-vision-doc-writing-sessions-iii/).
Closes https://github.com/rust-lang/wg-async-foundations/issues/95
=> Barbara anguishes over HTTP

.github/ISSUE_TEMPLATE/-shiny-vision--story-issue.md, src/vision/how_to_vision.md, src/vision/how_to_vision/shiny_future.md, src/vision/shiny_future.md, src/vision/shiny_future/template.md
Do the issue templates need to start with a - ? That makes working with them a bit annoying.
resolves #116
=> prep for shiny future

src/vision/shiny_future/barbara_makes_a_wish.md
This is a retelling of [Barbara wants Async Insights][].
I suspect the tool it outlines would have impact on other stories (which I did not take the time yet to evaluate; I hope that will get added before this is merged).
Also, the tool presented here would address other points raised in the [FAQ][wants FAQ] of that story. But I am also trying to provide a model of how I would like shiny future stories to be written, and so I did not attempt to address all those points in one narrative. Instead, I tried to provide one clear story. 
* (Well, okay, *two* stories, if you get to the time-traveling at the end...)
[Barbara wants Async Insights]: https://github.com/rust-lang/wg-async-foundations/blob/master/src/vision/status_quo/barbara_wants_async_insights.md
[wants FAQ]: …
=> shiny future: Barbara makes a wish

src/vision/status_quo/alan_thinks_he_needs_async_locks.md, src/vision/status_quo/alan_tries_a_socket_sink.md
This story comes from an async writing session with @LucioFranco and @Darksonn.
=> Add Alan thinks he needs async locks

src/vision/status_quo/alan_builds_a_cache.md
This story is built upon the [meeing notes](https://hackmd.io/VvCd4IOnQneLlVKl4sr8Dg?view) and a discussion that happened in #65.
I'd love to iterate on that and polish it, please let me know how to make it better :) 🙏
=> Alan builds a cache

src/vision/status_quo/barbara_bridges_sync_and_async.md
Cowritten with participants from writing workshop on 2021-04-02 at 14:30:
* Doc Jones
* Andrew Chin
* Emmanuel
* Frederik
* Zeeshan
* Trevor
* Ivan Tham
Closes https://github.com/rust-lang/wg-async-foundations/issues/54
=> add story about bridging sync and async

src/vision/shiny_future/alans_trust_in_the_compiler_is_rewarded.md
This actually isn't all, I think these shiny futures are really connected to quite a number of status quo stories.
=> link another status quo story

src/vision/shiny_future/template.md
Here are some streamlined FAQs for shiny future stories.
=> propose alternative FAQs for shiny futures

src/vision/status_quo.md, src/vision/status_quo/barbara_tries_unix_socket.md
Fix #190
Rendered https://github.com/pickfire/wg-async-foundations/blob/ready/src/vision/status_quo/barbara_tries_unix_socket.md
cc @Stupremee
=> Status quo barbara tries unix socket

src/vision/shiny_future/alan_learns_async_on_his_own.md
This is the story of Alan's first foray into the world of async Rust in a shiny future where everything is more helpful.
I went a bit overboard — once I started writing it was hard to stop 😅 
I'm hoping I make @estebank happy with some of the proposed warnings/errors.
[Rendered](https://github.com/jonhoo/wg-async-foundations/blob/learning-async/src/vision/shiny_future/alan_learns_async_on_his_own.md).
[Related HackMD from conversation with Alice that lead to this doc](https://hackmd.io/@XdLd8qq_Q7WlqJsDitWMFQ/SyD5KHuOO).
/cc @Darksonn
=> Shiny future: Alan learns async on his own.

src/vision/shiny_future/barbara_wants_async_rw.md
Shiny future story where there is a common abstraction for buffered `AsyncRead`/`AsyncWrite` that is implemented by all `async` runtimes.
=> Shiny Future: Buffered Async Read/Write

src/vision/status_quo/grace_writes_a_new_fb_service.md
This is currently an outline, similar in style to @nikomatsakis's life of an AWS engineer story.
=> Add life of a Facebook C++ engineer status quo story

src/vision/status_quo/alan_tries_processing_some_files.md
I recently found https://blog.rust-lang.org/2021/03/18/async-vision-doc.html, and thought I'd contribute my experience as someone learning new to `async` Rust (and Rust in general).
=> status quo: Alan tries processing some files

src/vision/how_to_vision.md, src/vision/shiny_future.md, src/vision/status_quo.md
The brainstorming period has come to an end! As the how to vision page now says: 
> The process we are using to write the vision doc encourages active collaboration and "positive sum" thinking. We started with a brainstorming period, during which we collected as many "status quo" and "shiny future" stories as we can. We are currently wrapping up that phase. We will still accept new PRs if people produce them, but we are no longer soliciting new stories. We would like to offer a [hearty thanks](https://rust-lang.github.io/wg-async-foundations/acknowledgments.html) to the many people who participated in this effort!
>
> We are now entering the "harmoniing period", and the working group ar assembling the various stories and shiny futures into a coherent draft. This draft will be reviewed by …
=> End of the brainstorming period

src/vision/status_quo/barbara_builds_an_async_executor.md
One of the two issues identified in my call with @nikomatsakis is the time aspects that may be present in the decisions of when to build something new or improve the ecosystem.
Rather than writing a totally new story about it, I decided to add this as part of the motivation in Barbara's story.
The rest of her experience is very similar to mine.
=> minor changes to Barbara's story

src/vision/status_quo/barbara_wishes_for_easy_runtime_switch.md
This story is the outcome of our status-quo brainstorming session on Wed Apr 28, 2021.
=> status quo story: Barbara wishes for an easy runtime switch

src/vision/status_quo/alan_wants_prefetch_iterator.md
[Rendered](https://github.com/rust-lang/wg-async-foundations/blob/7614fb569f62591601530b747657e6ab86529b89/src/vision/status_quo/alan_wants_prefetch_iterator.md)
=> Added story about Alan writing a prefetch iterator

src/vision/status_quo/alan_creates_a_hanging_alarm.md
I wanted to share some of my experience using Rust async. I tried to follow the instructions but following instructions isn't always my strong suit so let me know...
=> status_quo: bottlerocket canary hangs

src/vision/status_quo/barbara_wants_single_threaded_optimizations.md
Hopefully I can sneak this in while we're still in the "winding down" phase for the status quo!
Closes #212.
=> Add story for library Send-ness.

src/vision/status_quo/barbara_benchmarks_async_trait.md
Thanks to @joshlf and @brunowonka for helping write this.﻿
=> Barbara begets backpressure and benchmarks async_trait

src/vision/status_quo/barbara_polls_a_mutex.md
This is a rough vision about some complexities I ran into trying to poll async mutexes.
=> Add src/vision/status_quo/barbara_polls_a_mutex.md

src/vision/submitted_stories/status_quo/alan_wants_prefetch_iterator.md
Fixes to some typos and other minor edits I came across while reading through some of the status quo stories.
=> Minor edits

src/vision/roadmap/polish/lint_must_not_suspend.md
Adds information about what is blocking the current stabilization, let me know what else I should add!
=> improve information on must_not_suspend page

src/CHARTER.md, src/SUMMARY.md, src/welcome.md
- Create basic charter from content on home page
- Add membership requirements
=> Add charter with membership requirements

src/vision/roadmap.md
As discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async/topic/Async.20main.20and.20tests.20state.20of.20the.20art) this zone require some experimentation that I'm happy to drive in.
With this PR I will ask in a formal way to be the owner of this task, and I will add successive PR to complete the following steps
- A landing page exists 
- Milestones are defined on the landing page 
- Stakeholders are identified and looped in at the proper stages
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>
=> ask to owning the async main and test task

src/vision/how_it_feels.md
=> docs: fix typo

src/meetings.md
The meeting time has changed. I'm not sure when. I scooped up the meeting notes that seemed obvious to find; I'm not sure if I missed some of the notes or if those meetings never happened.
=> update meeting time; collect recent meeting notes

src/CHARTER.md
=> Fix link to wg membership
